apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-discovery-client
  namespace: default
rules:
  - apiGroups: ["", "extensions", "apps"] # "" indicates the core API group
    resources: ["services", "pods", "configmaps", "endpoints"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-discovery-client-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: api-service-account
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: service-discovery-client
  apiGroup: rbac.authorization.k8s.io

